### PR TITLE
Branch bug fixes

### LINKED ISSUE #149: [PE-D] Matched list does not update after editting student subjects
after matching tutors to mary
I edit the subjects take by mary

The result doesn't automatically update

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: softmagnet/ped#1

### LINKED ISSUE #150: [PE-D] "How to use command" message for `match` is incorrect
## Command
`match`

## Observed behaviour

Parameters are stated to be `s/t INDEX`

## Expected behaviour

Parameters should be `INDEX` since `match` does not take in the `s/t` preamble

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: xlzior/ped#3

### LINKED ISSUE #159: [PE-D] When I match a student and then edit/delete the student, the match list does not get updated
## Steps to reproduce

(optional but preferred: clear teachers and students)

1. Create a teacher e.g. `add t n/John Doe p/98765432 g/M q/2 t/PM TE TM TL`
2. Create a student e.g. `a s n/Mary Sue p/98765432 g/F r/Wants tutor urgently t/PM PE` who shares a subject with the teacher
3. `match 1` to try to match the student. match list shows the teacher
4. `edit s 1 t/PS` to change the student's subjects to something that the teacher does not teach. alternatively `delete s 1` or `clear s` to delete the student

## Observed behaviour

Match list does not get updated and still shows the teacher, even though the teacher is no longer a match for the student

## Expected behaviour

Match list should be cleared when I update a student, or the match list should update to show a new list of teachers that match the student

Interestingly, when I do other changes like adding a new teacher who could teach that student, the match list gets updated appropriately (which was a plus point I did not expect)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: xlzior/ped#5

### LINKED ISSUE #170: [PE-D] after deleting student, the matched list still shows
i enter `match 1`
and there is a non-empty list of tutors in matched list
then I enter `delete s 1`
the student gets deleted but the matched list of that deleted student is still there

furthermore you can even continue to use filter command on that list even that list is not related to anything already

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: softmagnet/ped#6

### PR DESCRIPTION
**Pull request by zihaooo9**
Fixes in this PR:
- fixed match command error messages
- fix the issue where editing/deleting matched student does not update match list

Resolves #149, Resolves #150, Resolves #159, Resolves #170

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -65,4 +65,20 @@ public static boolean isNonZeroUnsignedInteger(String s) {
             return false;
         }
     }
+
+    /**
+     * @@author baeldung-reused
```
Comment (tenebrius1) [inline src/main/java/seedu/address/commons/util/StringUtil.java:70]: If I'm not wrong this is supposed to be `zihaooo9-reused`. I remember someone asking it in the forum before

File: src/main/java/seedu/address/logic/parser/MatchCommandParser.java [hunk 2]
```diff
@@ -19,14 +21,19 @@
     public MatchCommand parse(String args) throws ParseException {
         requireNonNull(args);
         ArgumentMultimap argMultimap = ArgumentTokenizer.tokenize(args);
+        String preamble = argMultimap.getPreamble().trim();
+        // Check if argument passed is a number or not
+        if (!StringUtil.isNumeric(preamble)) {
```
Comment (tenebrius1) [inline src/main/java/seedu/address/logic/parser/MatchCommandParser.java:26]: Shouldn't you check for integer instead of numeric?

File: src/main/java/seedu/address/commons/util/StringUtil.java (hunk 1 above)
Comment (Lemonsr) [reply src/main/java/seedu/address/commons/util/StringUtil.java:70]: https://nus-cs2103-ay2122s1.github.io/website/schedule/week12/admin.html#policy-on-reuse

File: src/main/java/seedu/address/logic/parser/MatchCommandParser.java (hunk 2 above)
Comment (zihaooo9) [reply src/main/java/seedu/address/logic/parser/MatchCommandParser.java:26]: Changed as per our discussion.

File: src/test/java/seedu/address/model/ModelManagerTest.java [hunk 3]
```diff
@@ -209,9 +222,110 @@ public void updateMatchedTutor_modifyList_throwAssertionError() {
...
+        modelManager.filterMatchedTutor(predicate1);
+        cliTutors.removeTutor(ENZIO);
+        expectedTutorList = new FilteredList<>(cliTutors.getTutorList());
+        assertEquals(expectedTutorList, modelManager.getMatchedTutorList());
+        // Check matched student
+        assertEquals(DANIEL, modelManager.getMatchedStudent());
+
+        // filter out graduate qualification, no matches
+        ArrayList<Qualification> qualificationList = new ArrayList<>();
+        genderList.add(new Gender("F"));
```
Comment (knotstoks) [inline src/test/java/seedu/address/model/ModelManagerTest.java:278]: Perhaps you may try and kindly assist me in creating a femaleGender field instead of using `new Gender("F")`

But honestly doesnt really affect much

File: src/test/java/seedu/address/model/ModelManagerTest.java [hunk 4]
```diff
@@ -209,9 +222,110 @@ public void updateMatchedTutor_modifyList_throwAssertionError() {
...
+        ArrayList<Gender> genderList = new ArrayList<>();
+        genderList.add(new Gender("F"));
+        GenderContainsGenderPredicate predicate1 = new GenderContainsGenderPredicate(genderList);
+        modelManager.filterMatchedTutor(predicate1);
+        assertEquals(expectedStudent, modelManager.getMatchedStudent());
+
+        // After filtering to 0 matches
+        expectedStudent = null;
+        ArrayList<Qualification> qualificationList = new ArrayList<>();
+        genderList.add(new Gender("F"));
```
Comment (knotstoks) [inline src/test/java/seedu/address/model/ModelManagerTest.java:316]: Same as above ^

**Review by knotstoks — COMMENTED** [review]
Just the random nit of not putting `Gender("F")` as a parameter in `ModelTest`

Aside from that, LGTM! 🚀

**Review by knotstoks — APPROVED** [review]
LGTM! 🚀
