### PR TITLE
Fix issues found in PE-D

### LINKED ISSUE #171: [PE-D] Example screenshots for list command in UG do not demonstrate functionality of list well
Maybe the "before" screenshot should be pre-filtered

Example:

Before:

After:

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Zenlzb/ped#6

### LINKED ISSUE #174: [PE-D] Filter command expected outcome screenshots do not match expected behavior
Might have accidentally used screenshots from match command

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Zenlzb/ped#7

### LINKED ISSUE #177: [PE-D] filter command
the before picture doesn't make sense cos it shows an empty matched list but yet a filter command is gonna be called?  A bit confusing for the reader

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: softmagnet/ped#8

### LINKED ISSUE #182: [PE-D] Edit function allows the user to not actually "edit" an attribute
Originally if a tutor has TerMath as their tag, and I enter an edit command "edit t 1 t/TM", it isn't actually editing anything - should this return an error instead of accepting the input?

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: aakanshanarain/ped#12

### LINKED ISSUE #185: Editing a person with empty t/ will clear tags
Throw an error message if empty t/ is detected

### LINKED ISSUE #186: [PE-D] Incorrect screenshots in UG for filter command
I think the same screenshots that were used for match are used for filter.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: aakanshanarain/ped#8

### PR DESCRIPTION
**Pull request by kleonang**
What's done in this PR:
- [X] Updated UG images for list command (fixes #171)
- [X] Updated UG images for filter command (fixes #174, fixes #177, fixes #186)
- [X] Improve error message when "q/" is entered as a field for students (addresses #133, #144, #146, #163)
- [X] Improve error message for invalid indices (addresses #156, #167)
- [X] Prevent clearing tags when using empty "t/" command (fixes #185)
- [X] Improve error message when edited person has no changes (fixes #182)
- [X] Renamed PPP documents to adhere to file naming convention
- [X] Impose a 100-character limit for Remark (addresses #161)

Remaining fixes:
- [ ] Prevent a person from a tutor list and student list from having the same phone number (#184)

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/EditCommandParser.java [hunk 1]
```diff
@@ -39,53 +43,57 @@ public EditCommand parse(String args) throws ParseException {
...
+                } else {
+                    throw new ParseException(MESSAGE_INVALID_TUTOR_DISPLAYED_INDEX);
+                }
+            } else {
+                throw pe;
+            }
+        }
+        if (argMultimap.getValue(PREFIX_QUALIFICATION).isPresent()) {
+            if (personType.equals(PersonType.STUDENT)) {
+                throw new ParseException(MESSAGE_INVALID_INPUT_STUDENT_WITH_QUALIFICATION);
```
Comment (zihaooo9) [inline src/main/java/seedu/address/logic/parser/EditCommandParser.java:90]: Perhaps you could put the code from here to the end of the method into another method like a `checkParametersPresent` method? LOC for the whole `parsePerson` method seems pretty long now

**Review by zihaooo9 — COMMENTED** [review]
Small nit mentioned, apart from them, LGTM!

File: src/main/java/seedu/address/logic/parser/EditCommandParser.java [hunk 2]
```diff
@@ -39,53 +43,57 @@ public EditCommand parse(String args) throws ParseException {
...
-
-    private EditCommand handleStudent(String args) throws ParseException {
-        ArgumentMultimap studentMultimap =
-                ArgumentTokenizer.tokenize(args, PREFIX_NAME, PREFIX_PHONE, PREFIX_GENDER, PREFIX_REMARK, PREFIX_TAG);
-
-        EditStudentDescriptor editStudentDescriptor = new EditStudentDescriptor();
-        return parsePerson(studentMultimap, editStudentDescriptor, PersonType.STUDENT);
-    }
-
     private EditCommand parsePerson(ArgumentMultimap argMultimap, EditPersonDescriptor editPersonDescriptor,
```
Comment (Lemonsr) [inline src/main/java/seedu/address/logic/parser/EditCommandParser.java:62]: This function is over 30 LOC, might want to consider splitting it up? 🌞

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 3]
```diff
@@ -78,6 +78,8 @@
     public static final String INVALID_TAG = "ABCDE";
     public static final String INVALID_ZERO_INDEX = "0";
     public static final String INVALID_INDEX = "-69";
+    public static final String INVALID_INTEGER_MIN = Long.toString(Integer.MIN_VALUE + 1);
+    public static final String INVALID_INTEGER_MAX = Long.toString(Integer.MAX_VALUE + 1);
 
     public static final String PREAMBLE_WHITESPACE = "\t  \r  \n";
```
Comment (Lemonsr) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java:84]: Is this used? I think it wasn't used in my version so I was wondering if it should be deleted.

Comment (Lemonsr) [reply src/test/java/seedu/address/logic/commands/CommandTestUtil.java:84]: Same with `INVALID_REMARK_DESC` (it's not used) but you may want to add testcases that incorporate it's use instead of deleting it! 🧼

**Review by Lemonsr — COMMENTED** [review]
Some general comments! 🦖

File: src/test/java/seedu/address/logic/parser/EditCommandParserTest.java [hunk 4]
```diff
@@ -75,11 +79,27 @@ public void parse_missingParts_failure() {
...
+                MESSAGE_INVALID_TUTOR_DISPLAYED_INDEX);
 
         // zero index
         assertParseFailure(parser, VALID_STUDENT_LETTER + " " + INVALID_ZERO_INDEX + NAME_DESC_AMY,
-                MESSAGE_INVALID_FORMAT);
+                MESSAGE_INVALID_STUDENT_DISPLAYED_INDEX);
+        assertParseFailure(parser, VALID_TUTOR_LETTER + " " + INVALID_ZERO_INDEX + NAME_DESC_AMY,
+                MESSAGE_INVALID_TUTOR_DISPLAYED_INDEX);
+
+        // index greater than MAX_INT
```
[the remark this answers is not in the document]
Comment (kleonang) [reply src/test/java/seedu/address/logic/parser/EditCommandParserTest.java:92]: Yup, positive indices (that exceed the length of the tutor/student list) are tested in `EditCommandTest` instead as it needs to reference a `Model` to determine what index is out of bounds. The relevant tests in `EditCommandTest` are `execute_invalidTutorIndexFilteredTutorList_failure()` and `execute_invalidStudentIndexFilteredStudentList_failure()`.

**Review by knotstoks — APPROVED** [review]
LGTM! 🚀
