### PR TITLE
Fix Phone

### LINKED ISSUE #184: A person from the Tutor list and Student list can have the same phone number
Disallow this

### PR DESCRIPTION
**Pull request by zihaooo9**
Ensure that all phone numbers are unique across tutors and students

Resolves #184

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -124,11 +124,14 @@ private CommandResult executeEditTutor(Model model) throws CommandException {
...
         Tutor editedTutor = createEditedTutor(tutorToEdit, (EditTutorDescriptor) editPersonDescriptor);
 
+
         if (tutorToEdit.equals(editedTutor)) {
             throw new CommandException(MESSAGE_UNCHANGED_TUTOR);
         }
-        if (!tutorToEdit.isSamePerson(editedTutor) && model.hasTutor(editedTutor)) {
-            throw new CommandException(MESSAGE_DUPLICATE_TUTOR);
+
+        if (!tutorToEdit.getPhone().equals(editedTutor.getPhone())
```
Comment (tenebrius1) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:132]: Maybe you want to consider adding a comment here since this is quite difficult to understand 😅

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -160,8 +163,10 @@ private CommandResult executeEditStudent(Model model) throws CommandException {
         if (studentToEdit.equals(editedStudent)) {
             throw new CommandException(MESSAGE_UNCHANGED_STUDENT);
         }
-        if (!studentToEdit.isSamePerson(editedStudent) && model.hasStudent(editedStudent)) {
-            throw new CommandException(MESSAGE_DUPLICATE_STUDENT);
+
+        if (model.hasPersonWithSamePhone(editedStudent.getPhone())
```
Comment (tenebrius1) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:167]: Small nit but maybe you want to put the `!studentToEdit.getPhone().equals(editedStudent.getPhone()` before your `model.hasPersonWithSamePhone(editedStudent.getPhone()` since you did that for your tutor one

File: src/test/java/seedu/address/model/CliTutorsTest.java [hunk 3]
```diff
@@ -232,6 +238,18 @@ public void sortMatchedTutorList_validInputNoModification_success() {
...
+    @Test
+    public void hasPersonWithSamePhoneTest() {
+        TypicalPersons.getTypicalTutors().stream().forEach(tutor -> cliTutors.addTutor(tutor));
+        TypicalPersons.getTypicalStudents().stream().forEach(student -> cliTutors.addStudent(student));
+
+        Phone phone = new Phone("94351253");
+        assertTrue(cliTutors.hasPersonWithSamePhone(phone));
+
+        phone = new Phone("94351259");
+        assertFalse(cliTutors.hasPersonWithSamePhone(phone));
```
Comment (tenebrius1) [inline src/test/java/seedu/address/model/CliTutorsTest.java:250]: Maybe you want to use a variable instead of using magic numbers here?

File: src/test/java/seedu/address/model/ModelManagerTest.java [hunk 4]
```diff
@@ -328,7 +334,17 @@ public void getMatchedStudentTest() {
...
+    public void hasPersonWithSamePhoneTest() {
+        TypicalPersons.getTypicalTutors().stream().forEach(tutor -> modelManager.addTutor(tutor));
+        TypicalPersons.getTypicalStudents().stream().forEach(student -> modelManager.addStudent(student));
+
+        Phone phone = new Phone("94351253");
+        assertTrue(modelManager.hasPersonWithSamePhone(phone));
 
+        phone = new Phone("94351259");
+        assertFalse(modelManager.hasPersonWithSamePhone(phone));
+    }
```
Comment (tenebrius1) [inline src/test/java/seedu/address/model/ModelManagerTest.java:347]: Same issue as above

**Review by tenebrius1 — APPROVED** [review]
LGTM 🚀
