### PR TITLE
Fix name

### LINKED ISSUE #138: Auto Capitalize and trim whitespaces for name
Names should be capitalized

### PR DESCRIPTION
**Pull request by zihaooo9**
Auto capitalise and trim whitespace

Resolves #138

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ClearCommand.java [hunk 1]
```diff
@@ -15,9 +14,10 @@
     public static final String COMMAND_WORD = "clear";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD
-            + ": Clears all entries of tutors or students from the database. "
+            + ": Clears all entries of tutors or students from the database "
```
Comment (tenebrius1) [inline src/main/java/seedu/address/logic/commands/ClearCommand.java:17]: Should there be a `\n` at the end of the line here so that parameters appears on the next line?

File: src/main/java/seedu/address/logic/commands/ListCommand.java [hunk 2]
```diff
@@ -17,9 +17,10 @@
     public static final String COMMAND_ALIAS = "l";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD
-            + ": Lists all entries of tutors or students. "
+            + ": Lists all entries of tutors or students "
```
Comment (tenebrius1) [inline src/main/java/seedu/address/logic/commands/ListCommand.java:20]: Same issue here, I think there should be a `\n`

File: src/main/java/seedu/address/model/person/Name.java [hunk 3]
```diff
@@ -33,10 +37,32 @@ public static boolean isValidName(String test) {
         return test.matches(VALIDATION_REGEX);
     }
 
+    /**
+     * Formats the name by capitalizing the first character and removing unnecessary whitespaces.
+     *
+     * @return formatted name.
+     */
+    public String formatName() {
```
Comment (tenebrius1) [inline src/main/java/seedu/address/model/person/Name.java:45]: Small thing but I think the method name can be `formatFullName` instead?

**Review by tenebrius1 — APPROVED** [review]
LGTM!! 🚀
